name: Improved Security Build

on:
  push:
    branches:
      - main
      - feature/pipeline

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          sonar.organization: anjulasjay99
          sonar.projectKey: anjulasjay99_fuel-management-backend-ssd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run OWASP Zap Baseline scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: "https://admin-rpms.netlify.app/login"

      - name: Snyk security check
        uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --print-deps --severity-threshold=high

      - name: Secret Exposure Scan with gitleaks
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: gitleaks.toml

      - name: Output Snyk report
        run: cat snyk.json | jq

      - name: Install dependencies
        run: npm install

      - name: Audit dependencies
        run: npm audit --audit-level=moderate
